- .github/workflows/api-doc.yml
- .github/workflows/api-lint.yml
- .github/workflows/api-schema-lint.yml
- src/main/resources/swagger.api/consortia.yaml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
> FOLIO-3678 MODCONSKC-1 Use GitHub Workflows api-lint and api-schema-lint and api-doc

- pom.xml
- src/test/java/org/folio/consortia/FolioConsortiaApplicationTest.java
- src/test/java/org/folio/consortia/config/FolioExecutionContextBuilderTest.java
- src/test/java/org/folio/consortia/service/SharingInstanceServiceTest.java
- src/test/java/org/folio/consortia/service/UserTenantServiceTest.java
The official version of Spring for Quesnelia is 3.2 (see https://wiki.folio.org/display/TC/Quesnelia).
- Upgrade Spring Boot parent version and affected libraries, plugins
environment. Communication is paramount if that is …
> MODCONSKC-2 Upgrade to Spring 3.2

- src/main/java/org/folio/consortia/controller/SelfController.java
- src/main/java/org/folio/consortia/domain/dto/Payload.java
- src/main/java/org/folio/consortia/utils/TokenUtils.java
[MODCONSKC-5](https://folio-org.atlassian.net/browse/MODCONSKC-5)
- add alternative source of `user_id`
> MODCONSKC-5: fix user id extracting

- NEW.md
- descriptors/ModuleDescriptor-template.json
There is a 403 error while institutional tenant registration.
- add missing permissions
- add NEWS.md file …
> FIX: update module descriptor with user section permissions

- Jenkinsfile
Related Jira Ticket:
[RANCHER-1515: prepare & merge PRs for RANCHER-1502 part1](https://folio-org.atlassian.net/browse/RANCHER-1515)
> RANCHER-1515: build Container Image for application

- descriptors/ModuleDescriptor-template.json
Changes system user type from `module` to `system`
- Change system user type …
> EUREKA-225 Change system user type

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/MODCONSKC-35
> Release 1.4.5

- src/main/java/org/folio/consortia/domain/entity/SharingPolicyEntity.java
- src/main/java/org/folio/consortia/domain/entity/SharingRoleEntity.java
- src/main/java/org/folio/consortia/domain/entity/SharingSettingEntity.java
- src/main/java/org/folio/consortia/service/BaseSharingService.java
- src/main/java/org/folio/consortia/service/impl/SharingPolicyService.java
- src/main/java/org/folio/consortia/service/impl/SharingRoleCapabilityService.java
- src/main/java/org/folio/consortia/service/impl/SharingRoleCapabilitySetService.java
- src/main/java/org/folio/consortia/service/impl/SharingRoleService.java
- src/main/java/org/folio/consortia/service/impl/SharingSettingService.java
- src/test/java/org/folio/consortia/service/SharingPolicyServiceTest.java
- src/test/java/org/folio/consortia/service/SharingRoleServiceTest.java
- src/test/java/org/folio/consortia/service/SharingSettingServiceTest.java
- src/test/java/org/folio/consortia/support/EntityUtils.java
https://folio-org.atlassian.net/browse/MODCONSKC-21
Found issue in the creation of role entity where id is being set to null
- Fixed issue
- Using builder to avoid any such cases in the future
environment. Communication is …
> [MODCONSKC-21] - Fix creation of entities and role entity

- src/main/resources/db/changelog/changes/migrate-data-from-mod-consortia.xml
- src/test/java/org/folio/consortia/repository/ConsortiaMigrationTest.java
- src/test/resources/sql/consortia_data.sql
Fix consortia migration script for `tenant` table
US: [MODCONSKC-40](https://folio-org.atlassian.net/browse/MODCONSKC-40)
Add specific `setup_status` type casting
environment. Communication is paramount if that is to be …
> MODCONSKC-40: fix consortia migration script for tenant table

- src/main/resources/db/changelog/changelog-master.xml
- src/main/resources/db/changelog/changes/migrate-data-from-mod-consortia.xml
- src/main/resources/db/changelog/changes/migrate-tenant-data-from-mod-consortia.xml
- src/test/resources/sql/consortia_data.sql
Fix consortia migration script
Fix `pk_tenant_id` key duplication unique value constraint violation for tenant migration script
`mod_consortia` data to migrate:
`mod_consoria_keycloak` BEFORE migration:
`mod_consoria_keycloak` AFTER migration:
Ideally, all the PRs involved in breaking changes would be merged on the same day to avoid …
> MODCONSKC-40: fix pk_tenant_id key duplication unique value constraint violation for migration script

- descriptors/ModuleDescriptor-template.json
While it's helpful for reviewers to help identify potential problems, ensuring …
> MODCONSKC-41 inventory API version update

- NEWS.md
- pom.xml
Fixes broken release process:
1.4.2-SNAPSHOT -> 1.5.0-SNAPSHOT -> 1.4.5-SNAPSHOT
- Increase base snapshot version to be latest in terms of SemVer
- Next release must correspond current snapshot version - 1.5.1
environment. …
> MODCONSKC-44 Increase snapshot version to 1.5.1-SNAPSHOT

- pom.xml
[[MODCONSKC-45] Update libraries of dependant acq modules to the latest versions
](https://folio-org.atlassian.net/browse/MODCONSKC-45)
- Update versions
- Add module descriptor validator
> [MODCONSKC-45] Update libraries of dependant acq modules to the latest versions

- NEWS.md
- pom.xml
- src/main/resources/db/changelog/changelog-master.xml
- src/main/resources/db/changelog/changes/migrate-data-from-mod-consortia.xml
- src/main/resources/db/changelog/changes/migrate-tenant-data-from-mod-consortia.xml
- src/test/java/org/folio/consortia/repository/ConsortiaMigrationTest.java
- src/test/resources/sql/consortia_data.sql
Fix deployment issue on prod, cherry picked https://github.com/folio-org/mod-consortia-keycloak/pull/104/files
> MODCONSKC-40: fix pk_tenant_id key duplication unique value constraint violation for tenant migration script

- NEWS.md
- pom.xml
- src/main/resources/db/changelog/changelog-master.xml
- src/main/resources/db/changelog/changes/migrate-data-from-mod-consortia.xml
- src/main/resources/db/changelog/changes/migrate-user-tenant-data-from-mod-consortia.xml
- src/test/java/org/folio/consortia/repository/ConsortiaMigrationTest.java
- src/test/resources/sql/consortia_data.sql
While it's helpful for reviewers to help identify potential problems, ensuring …
> Hot Fix Release v1.5.1

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/FOLIO-4102
While it's helpful for …
> Release v1.6.0

- src/main/resources/db/changelog/changelog-master.xml
- src/main/resources/db/changelog/changes/migrate-safely-data-from-mod-consortia.xml
- src/main/resources/db/changelog/changes/migrate-tenant-data-from-mod-consortia.xml
- src/main/resources/db/changelog/changes/migrate-user-tenant-data-from-mod-consortia.xml
Fix consortia data migration
JIRA: [MODCONSKC-52](https://folio-org.atlassian.net/browse/MODCONSKC-52)
Add `ON CONFLICT DO NOTHING` which means to skip the insert operation and ignore an error if such occurs. The fixed case is the repeated insertions of the same data that were previously migrated. The case was reproducing for unique columns.
- Do PRs exist for these …
> MODCONSKC-52: fix consortia data migration for repeated rows with unique colums

- descriptors/ModuleDescriptor-template.json
Moved mod-users-bl dependency from optional to required section of module descriptor.
inter-team dependencies …
> Modconskc 50

- NEWS.md
- pom.xml
- src/main/java/org/folio/consortia/domain/dto/UserType.java
- src/main/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImpl.java
- src/main/java/org/folio/consortia/service/impl/UserServiceImpl.java
- src/test/java/org/folio/consortia/service/UserServiceTest.java
- src/test/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImplTest.java
Prepare for Ramsons 1.6.4 Bug Fix release that includes this fix
https://folio-org.atlassian.net/browse/MODCONSKC-58
> Ramsons 1.6.4 Bug Fix release

- NEWS.md
- pom.xml
- src/main/java/org/folio/consortia/service/impl/PublicationServiceImpl.java
- src/main/java/org/folio/consortia/utils/Constants.java
- src/test/java/org/folio/consortia/controller/TenantControllerTest.java
- src/test/java/org/folio/consortia/service/impl/PublicationServiceImplTest.java
https://folio-org.atlassian.net/browse/MODCONSKC-58
While it's helpful for …
> Bug Fix Release v1.6.5

- descriptors/ModuleDescriptor-template.json
Some required interfaces are not specified in Module Descriptor. This leads to excessive egress request routing though Kong, instead of direct calls to other module sidecars.
As expected results, Egress requests are routed directly to other module sidecars, Kong doesn’t process these requests
Add necessary interfaces to the module descriptor template
```sidecar-mod-consortia-keycloak,/null/roles/users/3fed7044-99ee-4487-90ce-19589715c457,2
sidecar-mod-consortia-keycloak,/classification-types,285
sidecar-mod-consortia-keycloak,/alternative-title-types,286
sidecar-mod-consortia-keycloak,/null/roles/users/bb6007f1-16cd-4955-b59e-86413a571076,2
sidecar-mod-consortia-keycloak,/null/roles/users/4c88d724-b5e5-4330-b06f-a5b16cb6da65,2
sidecar-mod-consortia-keycloak,/null/roles/users/f3a36848-859c- …
```
> MODCONSKC-60. Add missing required interfaces into Module descriptor

- src/main/java/org/folio/consortia/utils/TenantContextUtils.java
- src/test/java/org/folio/consortia/utils/TenantContextUtilsTest.java
While it's helpful for reviewers to help identify potential problems, ensuring …
> [MODCONSKC-57] - Fix Converting CaseSensitiveMap to Map

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
https://folio-org.atlassian.net/browse/MODCONSKC-56
While it's helpful for …
> Bug Fix Release v1.6.6

- src/main/java/org/folio/consortia/service/BaseSharingService.java
- src/main/java/org/folio/consortia/service/impl/SyncPrimaryAffiliationServiceImpl.java
- src/main/java/org/folio/consortia/service/impl/TenantServiceImpl.java
- src/main/java/org/folio/consortia/service/impl/UserAffiliationServiceImpl.java
- src/main/java/org/folio/consortia/service/impl/UserTenantServiceImpl.java
- <https://folio-org.atlassian.net/browse/MODCONSKC-68>
- Apply minor refactoring to replace `username` with `userId` and remove full object logging in each log marker
> [MODCONSKC-68]. PII in logs cleanup

- .github/workflows/api-doc.yml
- .github/workflows/api-lint.yml
- .github/workflows/api-schema-lint.yml
Enable workflow_dispatch
Keep the *.yml files in sync with the templates: https://github.com/folio-org/.github/tree/master/workflow-templates
> FOLIO-3944 Upgrade API-related Workflows

- descriptors/ModuleDescriptor-template.json
Update role-capabilities and user-capabilities interfaces version
While it's …
> Update role-capabilities and user-capabilities interfaces version

- Dockerfile
- Jenkinsfile
- pom.xml
- src/main/java/org/folio/consortia/utils/TenantContextUtils.java
- src/test/java/org/folio/consortia/base/BaseIT.java
- src/test/java/org/folio/consortia/base/BaseRepositoryTest.java
- src/test/java/org/folio/consortia/config/FolioExecutionContextBuilderTest.java
- src/test/java/org/folio/consortia/controller/ConsortiaConfigurationControllerTest.java
- src/test/java/org/folio/consortia/controller/ConsortiumControllerTest.java
- src/test/java/org/folio/consortia/controller/FolioTenantControllerTest.java
- src/test/java/org/folio/consortia/controller/PublicationControllerTest.java
- src/test/java/org/folio/consortia/controller/SelfControllerTest.java
- src/test/java/org/folio/consortia/controller/SharingInstanceControllerIntegrationTests.java
- src/test/java/org/folio/consortia/controller/SharingInstanceControllerTest.java
- src/test/java/org/folio/consortia/controller/SharingPolicyControllerTest.java
- src/test/java/org/folio/consortia/controller/SharingRoleCapabilityControllerTest.java
- src/test/java/org/folio/consortia/controller/SharingRoleCapabilitySetControllerTest.java
- src/test/java/org/folio/consortia/controller/SharingRoleControllerTest.java
- src/test/java/org/folio/consortia/controller/SharingSettingControllerTest.java
- src/test/java/org/folio/consortia/controller/TenantControllerTest.java
- src/test/java/org/folio/consortia/controller/UserTenantControllerTest.java
- src/test/java/org/folio/consortia/repository/ConsortiaMigrationTest.java
- src/test/java/org/folio/consortia/service/KeycloakServiceTest.java
- src/test/java/org/folio/consortia/support/extension/impl/OkapiExtension.java
[[FOLIO-4204] Update to mod-consortia Java 21](https://folio-org.atlassian.net/browse/FOLIO-4204)
Update java and dependency versions
> [FOLIO-4204] Update to mod-consortia Java 21

- descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODCONSKC-81
_Provide a brief technical summary of the changes._
---
> MODCONSKC-81. /_/proxy/tenants/{tenantId}/modules lacks okapi 1.9 interface
